package bo.com.jvargas.veterinaria.datos.model.sistema.enums;

import lombok.Getter;
import lombok.ToString;

@Getter
@ToString
public enum TipoProceso {
    INICIAR_SESION,
    GESTIONAR_CLIENTE,
    GESTIONAR_MASCOTA,
    GESTIONAR_AGENDA,
    GESTIONAR_PRODUCTO,
    GESTIONAR_VENTA,
    GESTIONAR_ATENCION,
    GESTIONAR_CONTROL_VACUNA,
    GESTIONAR_HISTORIAL,
    GESTIONAR_SERVICIO,
    GESTIONAR_REPORTE,
    GESTIONAR_CATEGORIA,
    GESTIONAR_ESTANTE,
    GESTIONAR_NOTA_SALIDA,
    GESTIONAR_NOTA_COMPRA,
    GESTIONAR_PROVEEDOR
}
